# https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: "Ubuntu bugs"
    url: https://bugs.launchpad.net/ubuntu/+source/wslu
    about: For Ubuntu version, you should not only report bug here but also report bug at Launchpad.