name: General Tests
on: [push]
jobs:
  generaltests:
    name: General Tests
    runs-on: windows-2019
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - uses: Vampire/setup-wsl@v1.2.0
        with:
          distribution: Ubuntu-20.04
          update: 'true'
          set-as-default: 'true'
          additional-packages:
            gzip
            make
            desktop-file-utils
            bats
            x11-apps
      - shell: wsl-bash -u root {0}
        run: |
          make
          make install
          make test


