name: General Tests
on: [push]
jobs:
  generaltests:
    name: General Tests
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Clone & import PsUWI
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name PsUWI -Scope CurrentUser -ErrorAction Stop
          Import-Module PsUWI
      - name: Creating running Instance
        run: |
          $WSLInstanceName = New-UbuntuWSLInstance -Release focal -Version 1 -NonInteractive -AdditionalPkg "make,gzip,desktop-file-utils"


